### ISSUE TITLE
False negative on certificate mismatch

### ISSUE THREAD

**Issue by tibod** [rbsec/sslscan#129] opened 2017-03-09 07:30 UTC
Example scanario below.
1) domain a.test.com with IP 127.0.0.1 and valid certificate for a.test.com
2) domain  z.otherpage.com also with ip 127.0.0.1.

When testing z.otherpage.com sslscan is not reporting certificate mismatch (as far as tested domain reffers to the IP related with original domain).

**Comment by rbsec** [comment] 2017-04-09 09:33
Dupe of #110

**Closed by rbsec** 2017-04-09 09:33 UTC
