### ISSUE TITLE
can't get 2.0.6 to correctly scan TLSv1.0 protocol

### ISSUE THREAD

**Issue by leonardocuei** [rbsec/sslscan#231] opened 2020-12-08 16:49 UTC
With sslscan 2.0.6, I cannot get it to correctly scan TLSv1.0 ciphers. I'm pretty sure TLSv1.0 is correctly enabled, a immuniweb.com scan clearly shows TLSv1.0 is activated. sslscan, however, always gives me:

```
[root@newmail ~]# sslscan --tls10 correio.XXXXXXXX.com.br:993
Version: 2.0.6
OpenSSL 1.1.1g FIPS  21 Apr 2020

Connected to 191.5.x.x

Testing SSL server correio.XXXXXXXX.com.br on port 993 using SNI name correio.XXXXXXXX.com.br

  SSL/TLS Protocols:
TLSv1.0   disabled
```

I'm running this from a CentOS 8 box which, by default, disabled TLSv1.0 systemwide. I have enabled LEGACY support and, by scanning other hosts (old ones, on CentOS 5 for example) i can see TLSv1.0 enabled, no problems, so it's not a problem on the scanning host

![immuniweb scan](https://user-images.githubusercontent.com/47743034/101514192-c67fbf00-395b-11eb-943d-8e26ca73b437.jpg)

**Comment by jtesta** [comment] 2020-12-08 17:08
> With sslscan 2.0.6, I cannot get it to correctly scan TLSv1.0 ciphers. 

I'd be happy to debug this, though I'd need a specific target that 
triggers the problem.  If you'd rather not post it publicly here, you 
can e-mail it to me via jtesta at-sign positronsecurity dot com.

**Comment by leonardocuei** [comment] 2020-12-08 17:14
Sure enough, emailing you two targets that i'm facing this situation.

**Comment by jtesta** [comment] 2020-12-08 22:31
@leonardocuei I was able to reproduce this against your private server (the one you asked me to use).  Turns out the code wasn't submitting the `supported_groups` extension during the `Client Hello` handshake; the TLS implementation on that target requires it, apparently.  I submitted PR #232 to fix this issue.  Can you try it against your more sensitive server and see if it works there as well?

**Comment by leonardocuei** [comment] 2020-12-08 23:11
> 
> 
> @leonardocuei I was able to reproduce this against your private server (the one you asked me to use). Turns out the code wasn't submitting the `supported_groups` extension during the `Client Hello` handshake; the TLS implementation on that target requires it, apparently. I submitted PR #232 to fix this issue. Can you try it against your more sensitive server and see if it works there as well?

be my guest, you can try it yourself, no problems.

**Comment by leonardocuei** [comment] 2020-12-08 23:13
it seems fine now, I can see TLsv1.0 enabled now! Thanks for the quick fix :)

**Comment by jtesta** [comment] 2020-12-08 23:14
Done.  My patch works against both your servers.

**Comment by rbsec** [comment] 2020-12-09 18:49
Hi @leonardocuei,

I've merged the PR that @jtesta made - I'll publish a new release shortly.

**Comment by leonardocuei** [comment] 2020-12-09 21:01
> 
> 
> Hi @leonardocuei,
> 
> I've merged the PR that @jtesta made - I'll publish a new release shortly.

awesome, thanks and glad for being able to help catch this situation :)

**Closed** 2020-12-10 11:45 UTC
